### ISSUE TITLE
Vulnerability disclosure: `bls` signatures leak the private key

### ISSUE THREAD

**Issue by str4d** [i18n-site/rust#1]
Hi! I'm one of the authors of `bls12_381`. I owned the `bls` crate name for 7 years, which I intended to use for https://github.com/str4d/bls (but I couldn't publish that crate at the time due to required dependencies not being published, and then life got in the way).

The crates.io team deleted the crate a few weeks ago and locked my account until today so I could not upload my code (which I intended to do once I realised). Before they finally unlocked my account, you uploaded your implementation.

Your implementation does not correctly implement BLS signatures, and leaks the private key in the signature, which makes it completely insecure to use. Specifically, this code:
https://github.com/i18n-site/rust/blob/0a7d4ac443eae6e99dae379424c28c832fcf16f6/bls/src/lib.rs#L57-L62

is computing $s = \mathsf{sk} \cdot \mathsf{Hash}(\mathsf{data})$, which means that the private key can be recovered from a single signature with $\mathsf{sk} = s \cdot \mathsf{Hash}(\mathsf{data})^{-1}$.

I have not reviewed the rest of your implementation for cryptographic vulnerabilities.

I would be very happy to take back the `bls` crate and publish my implementation to it instead. If you'd like to do this, please send an owner invite in crates.io to the user `str4d`.

**Comment by i18nsite** [comment]
![CleanShot 2024-07-17 at 17 26 29](https://github.com/user-attachments/assets/dce5a9bc-3af9-490c-86b3-e0366f780b81)

Already invited, please recycle the crate (I haven't officially used this crate yet).

I'm a website programmer and don't understand cryptography.

Hope to provide simple and easy-to-use interfaces, such as sign(sk,data), verfiy(pk,data,signature)

I hope it can support customizing the hash function.

Can be based on this https://docs.rs/digest/latest/digest/
Just provide a generic hash function interface

BLAKE3 implements this interface through feature=digest

https://github.com/BLAKE3-team/BLAKE3/blob/39e962e2bddf00a1786755c43c095c25b3b73a93/Cargo.toml#L102C1-L103C1
